/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./docs.html", "./verify.html", "./src/**/*.{js,html}"],
  safelist: [
    "bg-primary/10",
    "bg-tertiary-container/20",
    "text-primary",
    "text-tertiary",
    "text-secondary",
    "border-primary/30",
    "border-tertiary/30",
    "ring-primary/20",
    "ring-tertiary/20",
    "opacity-0",
    "opacity-100",
    "translate-y-6",
    "translate-y-0",
    "pointer-events-none",
    "border-tertiary/30",
    "bg-tertiary/10",
    "text-tertiary",
    "ring-2",
    "ring-tertiary/30",
  ],
  theme: {
    extend: {
      colors: {
        // M3 surface roles
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#434655",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: "#737686",
        "outline-variant": "#c3c6d7",
        "surface-tint": "#0053db",
        // Primary
        primary: "#004ac6",
        "on-primary": "#ffffff",
        "primary-container": "#2563eb",
        "on-primary-container": "#eeefff",
        "inverse-primary": "#b4c5ff",
        "primary-fixed": "#dbe1ff",
        "primary-fixed-dim": "#b4c5ff",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        // Secondary
        secondary: "#565e74",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2fd",
        "on-secondary-container": "#5c647a",
        "secondary-fixed": "#dae2fd",
        "secondary-fixed-dim": "#bec6e0",
        "on-secondary-fixed": "#131b2e",
        "on-secondary-fixed-variant": "#3f465c",
        // Tertiary
        tertiary: "#006242",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#007d55",
        "on-tertiary-container": "#bdffdb",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary-fixed": "#002113",
        "on-tertiary-fixed-variant": "#005236",
        // Error
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        // Background / surface-variant
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
      },
      fontFamily: {
        "display-lg": ["Geist", "Inter", "system-ui", "sans-serif"],
        "headline-md": ["Geist", "Inter", "system-ui", "sans-serif"],
        "body-base": ["Inter", "system-ui", "sans-serif"],
        "body-sm": ["Inter", "system-ui", "sans-serif"],
        "label-caps": ["Inter", "system-ui", "sans-serif"],
        "mono-code": ["JetBrains Mono", "ui-monospace", "monospace"],
        "mono-output": ["JetBrains Mono", "ui-monospace", "monospace"],
        display: ["Geist", "Inter", "system-ui", "sans-serif"],
        sans: ["Inter", "system-ui", "-apple-system", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        "display-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["20px", { lineHeight: "1.4", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-base": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }],
        "mono-code": ["14px", { lineHeight: "1.6", fontWeight: "500" }],
        "mono-output": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
      },
      spacing: {
        "margin-page": "2rem",
        gutter: "1.5rem",
        "section-gap": "3rem",
        "stack-gap": "1rem",
      },
      maxWidth: {
        container: "1600px",
      },
      borderRadius: {
        none: "0px",
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0 1px 2px rgba(16,24,40,0.06), 0 1px 3px rgba(16,24,40,0.10)",
        "card-hover": "0 4px 12px rgba(16,24,40,0.05)",
        sm: "0 1px 2px rgba(0,0,0,0.05)",
        md: "0 4px 6px rgba(0,0,0,0.07), 0 2px 4px rgba(0,0,0,0.05)",
      },
    },
  },
  plugins: [],
};
